# Generated by Django 4.1.2 on 2022-11-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="client_came",
            field=models.BooleanField(default=False),
        ),
    ]
