# Generated by Django 4.1.2 on 2022-11-23 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_trainer"),
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workout",
            name="user",
        ),
        migrations.AddField(
            model_name="workout",
            name="trainer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.trainer",
            ),
            preserve_default=False,
        ),
    ]
