# Generated by Django 4.1.2 on 2022-11-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0002_remove_workout_user_workout_trainer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="client_came",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
