# Generated by Django 4.1.2 on 2022-11-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0002_workout_client_came"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
