# Generated by Django 4.1.2 on 2022-12-07 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_trainer"),
        ("workouts", "0003_alter_workout_client_came"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workouts",
                to="clients.client",
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="trainer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workouts",
                to="users.trainer",
            ),
        ),
    ]
