# Generated by Django 4.1.2 on 2022-11-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0004_workoutexercise"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutexercise",
            name="description",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="workoutexercise",
            name="name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
