# Generated by Django 4.1.2 on 2022-11-18 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0005_workoutexercise_description_workoutexercise_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutexercise",
            name="workout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to="workouts.workout",
            ),
        ),
    ]
