# Generated by Django 4.1.2 on 2022-11-29 11:28

import clients.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_remove_client_client_user_client_trainer_client_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientPhotoSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_sets",
                        to="clients.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClientPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_path",
                    models.ImageField(
                        blank=True, null=True, upload_to=clients.models.upload_to
                    ),
                ),
                (
                    "photo_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="clients.clientphotoset",
                    ),
                ),
            ],
        ),
    ]
