# Generated by Django 4.1.2 on 2022-11-29 11:43

import django.db.models.deletion
from django.db import migrations, models

import clients.models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_clientphotoset_clientphoto"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestClientPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image_path",
                    models.ImageField(
                        blank=True, null=True, upload_to=clients.models.upload_to
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clients.client"
                    ),
                ),
            ],
        ),
    ]
