# Generated by Django 4.1.2 on 2022-12-12 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0006_clientmeasurement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="address",
        ),
    ]
