# Generated by Django 4.1.2 on 2022-11-23 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Client",
        ),
        migrations.DeleteModel(
            name="Trainer",
        ),
    ]
